
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Cuisinetype` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Cuisinetype
 * 
 */
export type CuisinetypeModel = runtime.Types.Result.DefaultSelection<Prisma.$CuisinetypePayload>

export type AggregateCuisinetype = {
  _count: CuisinetypeCountAggregateOutputType | null
  _avg: CuisinetypeAvgAggregateOutputType | null
  _sum: CuisinetypeSumAggregateOutputType | null
  _min: CuisinetypeMinAggregateOutputType | null
  _max: CuisinetypeMaxAggregateOutputType | null
}

export type CuisinetypeAvgAggregateOutputType = {
  id: number | null
}

export type CuisinetypeSumAggregateOutputType = {
  id: number | null
}

export type CuisinetypeMinAggregateOutputType = {
  id: number | null
  cuisine_type_name: string | null
}

export type CuisinetypeMaxAggregateOutputType = {
  id: number | null
  cuisine_type_name: string | null
}

export type CuisinetypeCountAggregateOutputType = {
  id: number
  cuisine_type_name: number
  _all: number
}


export type CuisinetypeAvgAggregateInputType = {
  id?: true
}

export type CuisinetypeSumAggregateInputType = {
  id?: true
}

export type CuisinetypeMinAggregateInputType = {
  id?: true
  cuisine_type_name?: true
}

export type CuisinetypeMaxAggregateInputType = {
  id?: true
  cuisine_type_name?: true
}

export type CuisinetypeCountAggregateInputType = {
  id?: true
  cuisine_type_name?: true
  _all?: true
}

export type CuisinetypeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Cuisinetype to aggregate.
   */
  where?: Prisma.CuisinetypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Cuisinetypes to fetch.
   */
  orderBy?: Prisma.CuisinetypeOrderByWithRelationInput | Prisma.CuisinetypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CuisinetypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Cuisinetypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Cuisinetypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Cuisinetypes
  **/
  _count?: true | CuisinetypeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CuisinetypeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CuisinetypeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CuisinetypeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CuisinetypeMaxAggregateInputType
}

export type GetCuisinetypeAggregateType<T extends CuisinetypeAggregateArgs> = {
      [P in keyof T & keyof AggregateCuisinetype]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCuisinetype[P]>
    : Prisma.GetScalarType<T[P], AggregateCuisinetype[P]>
}




export type CuisinetypeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CuisinetypeWhereInput
  orderBy?: Prisma.CuisinetypeOrderByWithAggregationInput | Prisma.CuisinetypeOrderByWithAggregationInput[]
  by: Prisma.CuisinetypeScalarFieldEnum[] | Prisma.CuisinetypeScalarFieldEnum
  having?: Prisma.CuisinetypeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CuisinetypeCountAggregateInputType | true
  _avg?: CuisinetypeAvgAggregateInputType
  _sum?: CuisinetypeSumAggregateInputType
  _min?: CuisinetypeMinAggregateInputType
  _max?: CuisinetypeMaxAggregateInputType
}

export type CuisinetypeGroupByOutputType = {
  id: number
  cuisine_type_name: string
  _count: CuisinetypeCountAggregateOutputType | null
  _avg: CuisinetypeAvgAggregateOutputType | null
  _sum: CuisinetypeSumAggregateOutputType | null
  _min: CuisinetypeMinAggregateOutputType | null
  _max: CuisinetypeMaxAggregateOutputType | null
}

type GetCuisinetypeGroupByPayload<T extends CuisinetypeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CuisinetypeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CuisinetypeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CuisinetypeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CuisinetypeGroupByOutputType[P]>
      }
    >
  >



export type CuisinetypeWhereInput = {
  AND?: Prisma.CuisinetypeWhereInput | Prisma.CuisinetypeWhereInput[]
  OR?: Prisma.CuisinetypeWhereInput[]
  NOT?: Prisma.CuisinetypeWhereInput | Prisma.CuisinetypeWhereInput[]
  id?: Prisma.IntFilter<"Cuisinetype"> | number
  cuisine_type_name?: Prisma.StringFilter<"Cuisinetype"> | string
  meals?: Prisma.MealListRelationFilter
}

export type CuisinetypeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  cuisine_type_name?: Prisma.SortOrder
  meals?: Prisma.MealOrderByRelationAggregateInput
}

export type CuisinetypeWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.CuisinetypeWhereInput | Prisma.CuisinetypeWhereInput[]
  OR?: Prisma.CuisinetypeWhereInput[]
  NOT?: Prisma.CuisinetypeWhereInput | Prisma.CuisinetypeWhereInput[]
  cuisine_type_name?: Prisma.StringFilter<"Cuisinetype"> | string
  meals?: Prisma.MealListRelationFilter
}, "id">

export type CuisinetypeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  cuisine_type_name?: Prisma.SortOrder
  _count?: Prisma.CuisinetypeCountOrderByAggregateInput
  _avg?: Prisma.CuisinetypeAvgOrderByAggregateInput
  _max?: Prisma.CuisinetypeMaxOrderByAggregateInput
  _min?: Prisma.CuisinetypeMinOrderByAggregateInput
  _sum?: Prisma.CuisinetypeSumOrderByAggregateInput
}

export type CuisinetypeScalarWhereWithAggregatesInput = {
  AND?: Prisma.CuisinetypeScalarWhereWithAggregatesInput | Prisma.CuisinetypeScalarWhereWithAggregatesInput[]
  OR?: Prisma.CuisinetypeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CuisinetypeScalarWhereWithAggregatesInput | Prisma.CuisinetypeScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Cuisinetype"> | number
  cuisine_type_name?: Prisma.StringWithAggregatesFilter<"Cuisinetype"> | string
}

export type CuisinetypeCreateInput = {
  cuisine_type_name: string
  meals?: Prisma.MealCreateNestedManyWithoutCuisine_relInput
}

export type CuisinetypeUncheckedCreateInput = {
  id?: number
  cuisine_type_name: string
  meals?: Prisma.MealUncheckedCreateNestedManyWithoutCuisine_relInput
}

export type CuisinetypeUpdateInput = {
  cuisine_type_name?: Prisma.StringFieldUpdateOperationsInput | string
  meals?: Prisma.MealUpdateManyWithoutCuisine_relNestedInput
}

export type CuisinetypeUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  cuisine_type_name?: Prisma.StringFieldUpdateOperationsInput | string
  meals?: Prisma.MealUncheckedUpdateManyWithoutCuisine_relNestedInput
}

export type CuisinetypeCreateManyInput = {
  id?: number
  cuisine_type_name: string
}

export type CuisinetypeUpdateManyMutationInput = {
  cuisine_type_name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CuisinetypeUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  cuisine_type_name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CuisinetypeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cuisine_type_name?: Prisma.SortOrder
}

export type CuisinetypeAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type CuisinetypeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cuisine_type_name?: Prisma.SortOrder
}

export type CuisinetypeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cuisine_type_name?: Prisma.SortOrder
}

export type CuisinetypeSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type CuisinetypeScalarRelationFilter = {
  is?: Prisma.CuisinetypeWhereInput
  isNot?: Prisma.CuisinetypeWhereInput
}

export type CuisinetypeCreateNestedOneWithoutMealsInput = {
  create?: Prisma.XOR<Prisma.CuisinetypeCreateWithoutMealsInput, Prisma.CuisinetypeUncheckedCreateWithoutMealsInput>
  connectOrCreate?: Prisma.CuisinetypeCreateOrConnectWithoutMealsInput
  connect?: Prisma.CuisinetypeWhereUniqueInput
}

export type CuisinetypeUpdateOneRequiredWithoutMealsNestedInput = {
  create?: Prisma.XOR<Prisma.CuisinetypeCreateWithoutMealsInput, Prisma.CuisinetypeUncheckedCreateWithoutMealsInput>
  connectOrCreate?: Prisma.CuisinetypeCreateOrConnectWithoutMealsInput
  upsert?: Prisma.CuisinetypeUpsertWithoutMealsInput
  connect?: Prisma.CuisinetypeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CuisinetypeUpdateToOneWithWhereWithoutMealsInput, Prisma.CuisinetypeUpdateWithoutMealsInput>, Prisma.CuisinetypeUncheckedUpdateWithoutMealsInput>
}

export type CuisinetypeCreateWithoutMealsInput = {
  cuisine_type_name: string
}

export type CuisinetypeUncheckedCreateWithoutMealsInput = {
  id?: number
  cuisine_type_name: string
}

export type CuisinetypeCreateOrConnectWithoutMealsInput = {
  where: Prisma.CuisinetypeWhereUniqueInput
  create: Prisma.XOR<Prisma.CuisinetypeCreateWithoutMealsInput, Prisma.CuisinetypeUncheckedCreateWithoutMealsInput>
}

export type CuisinetypeUpsertWithoutMealsInput = {
  update: Prisma.XOR<Prisma.CuisinetypeUpdateWithoutMealsInput, Prisma.CuisinetypeUncheckedUpdateWithoutMealsInput>
  create: Prisma.XOR<Prisma.CuisinetypeCreateWithoutMealsInput, Prisma.CuisinetypeUncheckedCreateWithoutMealsInput>
  where?: Prisma.CuisinetypeWhereInput
}

export type CuisinetypeUpdateToOneWithWhereWithoutMealsInput = {
  where?: Prisma.CuisinetypeWhereInput
  data: Prisma.XOR<Prisma.CuisinetypeUpdateWithoutMealsInput, Prisma.CuisinetypeUncheckedUpdateWithoutMealsInput>
}

export type CuisinetypeUpdateWithoutMealsInput = {
  cuisine_type_name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CuisinetypeUncheckedUpdateWithoutMealsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  cuisine_type_name?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type CuisinetypeCountOutputType
 */

export type CuisinetypeCountOutputType = {
  meals: number
}

export type CuisinetypeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  meals?: boolean | CuisinetypeCountOutputTypeCountMealsArgs
}

/**
 * CuisinetypeCountOutputType without action
 */
export type CuisinetypeCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CuisinetypeCountOutputType
   */
  select?: Prisma.CuisinetypeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CuisinetypeCountOutputType without action
 */
export type CuisinetypeCountOutputTypeCountMealsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MealWhereInput
}


export type CuisinetypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  cuisine_type_name?: boolean
  meals?: boolean | Prisma.Cuisinetype$mealsArgs<ExtArgs>
  _count?: boolean | Prisma.CuisinetypeCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["cuisinetype"]>

export type CuisinetypeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  cuisine_type_name?: boolean
}, ExtArgs["result"]["cuisinetype"]>

export type CuisinetypeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  cuisine_type_name?: boolean
}, ExtArgs["result"]["cuisinetype"]>

export type CuisinetypeSelectScalar = {
  id?: boolean
  cuisine_type_name?: boolean
}

export type CuisinetypeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "cuisine_type_name", ExtArgs["result"]["cuisinetype"]>
export type CuisinetypeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  meals?: boolean | Prisma.Cuisinetype$mealsArgs<ExtArgs>
  _count?: boolean | Prisma.CuisinetypeCountOutputTypeDefaultArgs<ExtArgs>
}
export type CuisinetypeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type CuisinetypeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $CuisinetypePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Cuisinetype"
  objects: {
    meals: Prisma.$MealPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    cuisine_type_name: string
  }, ExtArgs["result"]["cuisinetype"]>
  composites: {}
}

export type CuisinetypeGetPayload<S extends boolean | null | undefined | CuisinetypeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CuisinetypePayload, S>

export type CuisinetypeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CuisinetypeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CuisinetypeCountAggregateInputType | true
  }

export interface CuisinetypeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Cuisinetype'], meta: { name: 'Cuisinetype' } }
  /**
   * Find zero or one Cuisinetype that matches the filter.
   * @param {CuisinetypeFindUniqueArgs} args - Arguments to find a Cuisinetype
   * @example
   * // Get one Cuisinetype
   * const cuisinetype = await prisma.cuisinetype.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CuisinetypeFindUniqueArgs>(args: Prisma.SelectSubset<T, CuisinetypeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CuisinetypeClient<runtime.Types.Result.GetResult<Prisma.$CuisinetypePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Cuisinetype that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CuisinetypeFindUniqueOrThrowArgs} args - Arguments to find a Cuisinetype
   * @example
   * // Get one Cuisinetype
   * const cuisinetype = await prisma.cuisinetype.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CuisinetypeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CuisinetypeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CuisinetypeClient<runtime.Types.Result.GetResult<Prisma.$CuisinetypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Cuisinetype that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CuisinetypeFindFirstArgs} args - Arguments to find a Cuisinetype
   * @example
   * // Get one Cuisinetype
   * const cuisinetype = await prisma.cuisinetype.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CuisinetypeFindFirstArgs>(args?: Prisma.SelectSubset<T, CuisinetypeFindFirstArgs<ExtArgs>>): Prisma.Prisma__CuisinetypeClient<runtime.Types.Result.GetResult<Prisma.$CuisinetypePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Cuisinetype that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CuisinetypeFindFirstOrThrowArgs} args - Arguments to find a Cuisinetype
   * @example
   * // Get one Cuisinetype
   * const cuisinetype = await prisma.cuisinetype.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CuisinetypeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CuisinetypeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CuisinetypeClient<runtime.Types.Result.GetResult<Prisma.$CuisinetypePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Cuisinetypes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CuisinetypeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Cuisinetypes
   * const cuisinetypes = await prisma.cuisinetype.findMany()
   * 
   * // Get first 10 Cuisinetypes
   * const cuisinetypes = await prisma.cuisinetype.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const cuisinetypeWithIdOnly = await prisma.cuisinetype.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CuisinetypeFindManyArgs>(args?: Prisma.SelectSubset<T, CuisinetypeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CuisinetypePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Cuisinetype.
   * @param {CuisinetypeCreateArgs} args - Arguments to create a Cuisinetype.
   * @example
   * // Create one Cuisinetype
   * const Cuisinetype = await prisma.cuisinetype.create({
   *   data: {
   *     // ... data to create a Cuisinetype
   *   }
   * })
   * 
   */
  create<T extends CuisinetypeCreateArgs>(args: Prisma.SelectSubset<T, CuisinetypeCreateArgs<ExtArgs>>): Prisma.Prisma__CuisinetypeClient<runtime.Types.Result.GetResult<Prisma.$CuisinetypePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Cuisinetypes.
   * @param {CuisinetypeCreateManyArgs} args - Arguments to create many Cuisinetypes.
   * @example
   * // Create many Cuisinetypes
   * const cuisinetype = await prisma.cuisinetype.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CuisinetypeCreateManyArgs>(args?: Prisma.SelectSubset<T, CuisinetypeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Cuisinetypes and returns the data saved in the database.
   * @param {CuisinetypeCreateManyAndReturnArgs} args - Arguments to create many Cuisinetypes.
   * @example
   * // Create many Cuisinetypes
   * const cuisinetype = await prisma.cuisinetype.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Cuisinetypes and only return the `id`
   * const cuisinetypeWithIdOnly = await prisma.cuisinetype.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CuisinetypeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CuisinetypeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CuisinetypePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Cuisinetype.
   * @param {CuisinetypeDeleteArgs} args - Arguments to delete one Cuisinetype.
   * @example
   * // Delete one Cuisinetype
   * const Cuisinetype = await prisma.cuisinetype.delete({
   *   where: {
   *     // ... filter to delete one Cuisinetype
   *   }
   * })
   * 
   */
  delete<T extends CuisinetypeDeleteArgs>(args: Prisma.SelectSubset<T, CuisinetypeDeleteArgs<ExtArgs>>): Prisma.Prisma__CuisinetypeClient<runtime.Types.Result.GetResult<Prisma.$CuisinetypePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Cuisinetype.
   * @param {CuisinetypeUpdateArgs} args - Arguments to update one Cuisinetype.
   * @example
   * // Update one Cuisinetype
   * const cuisinetype = await prisma.cuisinetype.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CuisinetypeUpdateArgs>(args: Prisma.SelectSubset<T, CuisinetypeUpdateArgs<ExtArgs>>): Prisma.Prisma__CuisinetypeClient<runtime.Types.Result.GetResult<Prisma.$CuisinetypePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Cuisinetypes.
   * @param {CuisinetypeDeleteManyArgs} args - Arguments to filter Cuisinetypes to delete.
   * @example
   * // Delete a few Cuisinetypes
   * const { count } = await prisma.cuisinetype.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CuisinetypeDeleteManyArgs>(args?: Prisma.SelectSubset<T, CuisinetypeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Cuisinetypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CuisinetypeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Cuisinetypes
   * const cuisinetype = await prisma.cuisinetype.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CuisinetypeUpdateManyArgs>(args: Prisma.SelectSubset<T, CuisinetypeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Cuisinetypes and returns the data updated in the database.
   * @param {CuisinetypeUpdateManyAndReturnArgs} args - Arguments to update many Cuisinetypes.
   * @example
   * // Update many Cuisinetypes
   * const cuisinetype = await prisma.cuisinetype.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Cuisinetypes and only return the `id`
   * const cuisinetypeWithIdOnly = await prisma.cuisinetype.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CuisinetypeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CuisinetypeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CuisinetypePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Cuisinetype.
   * @param {CuisinetypeUpsertArgs} args - Arguments to update or create a Cuisinetype.
   * @example
   * // Update or create a Cuisinetype
   * const cuisinetype = await prisma.cuisinetype.upsert({
   *   create: {
   *     // ... data to create a Cuisinetype
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Cuisinetype we want to update
   *   }
   * })
   */
  upsert<T extends CuisinetypeUpsertArgs>(args: Prisma.SelectSubset<T, CuisinetypeUpsertArgs<ExtArgs>>): Prisma.Prisma__CuisinetypeClient<runtime.Types.Result.GetResult<Prisma.$CuisinetypePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Cuisinetypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CuisinetypeCountArgs} args - Arguments to filter Cuisinetypes to count.
   * @example
   * // Count the number of Cuisinetypes
   * const count = await prisma.cuisinetype.count({
   *   where: {
   *     // ... the filter for the Cuisinetypes we want to count
   *   }
   * })
  **/
  count<T extends CuisinetypeCountArgs>(
    args?: Prisma.Subset<T, CuisinetypeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CuisinetypeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Cuisinetype.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CuisinetypeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CuisinetypeAggregateArgs>(args: Prisma.Subset<T, CuisinetypeAggregateArgs>): Prisma.PrismaPromise<GetCuisinetypeAggregateType<T>>

  /**
   * Group by Cuisinetype.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CuisinetypeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CuisinetypeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CuisinetypeGroupByArgs['orderBy'] }
      : { orderBy?: CuisinetypeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CuisinetypeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCuisinetypeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Cuisinetype model
 */
readonly fields: CuisinetypeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Cuisinetype.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CuisinetypeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  meals<T extends Prisma.Cuisinetype$mealsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Cuisinetype$mealsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MealPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Cuisinetype model
 */
export interface CuisinetypeFieldRefs {
  readonly id: Prisma.FieldRef<"Cuisinetype", 'Int'>
  readonly cuisine_type_name: Prisma.FieldRef<"Cuisinetype", 'String'>
}
    

// Custom InputTypes
/**
 * Cuisinetype findUnique
 */
export type CuisinetypeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cuisinetype
   */
  select?: Prisma.CuisinetypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cuisinetype
   */
  omit?: Prisma.CuisinetypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CuisinetypeInclude<ExtArgs> | null
  /**
   * Filter, which Cuisinetype to fetch.
   */
  where: Prisma.CuisinetypeWhereUniqueInput
}

/**
 * Cuisinetype findUniqueOrThrow
 */
export type CuisinetypeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cuisinetype
   */
  select?: Prisma.CuisinetypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cuisinetype
   */
  omit?: Prisma.CuisinetypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CuisinetypeInclude<ExtArgs> | null
  /**
   * Filter, which Cuisinetype to fetch.
   */
  where: Prisma.CuisinetypeWhereUniqueInput
}

/**
 * Cuisinetype findFirst
 */
export type CuisinetypeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cuisinetype
   */
  select?: Prisma.CuisinetypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cuisinetype
   */
  omit?: Prisma.CuisinetypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CuisinetypeInclude<ExtArgs> | null
  /**
   * Filter, which Cuisinetype to fetch.
   */
  where?: Prisma.CuisinetypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Cuisinetypes to fetch.
   */
  orderBy?: Prisma.CuisinetypeOrderByWithRelationInput | Prisma.CuisinetypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Cuisinetypes.
   */
  cursor?: Prisma.CuisinetypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Cuisinetypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Cuisinetypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Cuisinetypes.
   */
  distinct?: Prisma.CuisinetypeScalarFieldEnum | Prisma.CuisinetypeScalarFieldEnum[]
}

/**
 * Cuisinetype findFirstOrThrow
 */
export type CuisinetypeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cuisinetype
   */
  select?: Prisma.CuisinetypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cuisinetype
   */
  omit?: Prisma.CuisinetypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CuisinetypeInclude<ExtArgs> | null
  /**
   * Filter, which Cuisinetype to fetch.
   */
  where?: Prisma.CuisinetypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Cuisinetypes to fetch.
   */
  orderBy?: Prisma.CuisinetypeOrderByWithRelationInput | Prisma.CuisinetypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Cuisinetypes.
   */
  cursor?: Prisma.CuisinetypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Cuisinetypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Cuisinetypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Cuisinetypes.
   */
  distinct?: Prisma.CuisinetypeScalarFieldEnum | Prisma.CuisinetypeScalarFieldEnum[]
}

/**
 * Cuisinetype findMany
 */
export type CuisinetypeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cuisinetype
   */
  select?: Prisma.CuisinetypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cuisinetype
   */
  omit?: Prisma.CuisinetypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CuisinetypeInclude<ExtArgs> | null
  /**
   * Filter, which Cuisinetypes to fetch.
   */
  where?: Prisma.CuisinetypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Cuisinetypes to fetch.
   */
  orderBy?: Prisma.CuisinetypeOrderByWithRelationInput | Prisma.CuisinetypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Cuisinetypes.
   */
  cursor?: Prisma.CuisinetypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Cuisinetypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Cuisinetypes.
   */
  skip?: number
  distinct?: Prisma.CuisinetypeScalarFieldEnum | Prisma.CuisinetypeScalarFieldEnum[]
}

/**
 * Cuisinetype create
 */
export type CuisinetypeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cuisinetype
   */
  select?: Prisma.CuisinetypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cuisinetype
   */
  omit?: Prisma.CuisinetypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CuisinetypeInclude<ExtArgs> | null
  /**
   * The data needed to create a Cuisinetype.
   */
  data: Prisma.XOR<Prisma.CuisinetypeCreateInput, Prisma.CuisinetypeUncheckedCreateInput>
}

/**
 * Cuisinetype createMany
 */
export type CuisinetypeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Cuisinetypes.
   */
  data: Prisma.CuisinetypeCreateManyInput | Prisma.CuisinetypeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Cuisinetype createManyAndReturn
 */
export type CuisinetypeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cuisinetype
   */
  select?: Prisma.CuisinetypeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Cuisinetype
   */
  omit?: Prisma.CuisinetypeOmit<ExtArgs> | null
  /**
   * The data used to create many Cuisinetypes.
   */
  data: Prisma.CuisinetypeCreateManyInput | Prisma.CuisinetypeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Cuisinetype update
 */
export type CuisinetypeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cuisinetype
   */
  select?: Prisma.CuisinetypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cuisinetype
   */
  omit?: Prisma.CuisinetypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CuisinetypeInclude<ExtArgs> | null
  /**
   * The data needed to update a Cuisinetype.
   */
  data: Prisma.XOR<Prisma.CuisinetypeUpdateInput, Prisma.CuisinetypeUncheckedUpdateInput>
  /**
   * Choose, which Cuisinetype to update.
   */
  where: Prisma.CuisinetypeWhereUniqueInput
}

/**
 * Cuisinetype updateMany
 */
export type CuisinetypeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Cuisinetypes.
   */
  data: Prisma.XOR<Prisma.CuisinetypeUpdateManyMutationInput, Prisma.CuisinetypeUncheckedUpdateManyInput>
  /**
   * Filter which Cuisinetypes to update
   */
  where?: Prisma.CuisinetypeWhereInput
  /**
   * Limit how many Cuisinetypes to update.
   */
  limit?: number
}

/**
 * Cuisinetype updateManyAndReturn
 */
export type CuisinetypeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cuisinetype
   */
  select?: Prisma.CuisinetypeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Cuisinetype
   */
  omit?: Prisma.CuisinetypeOmit<ExtArgs> | null
  /**
   * The data used to update Cuisinetypes.
   */
  data: Prisma.XOR<Prisma.CuisinetypeUpdateManyMutationInput, Prisma.CuisinetypeUncheckedUpdateManyInput>
  /**
   * Filter which Cuisinetypes to update
   */
  where?: Prisma.CuisinetypeWhereInput
  /**
   * Limit how many Cuisinetypes to update.
   */
  limit?: number
}

/**
 * Cuisinetype upsert
 */
export type CuisinetypeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cuisinetype
   */
  select?: Prisma.CuisinetypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cuisinetype
   */
  omit?: Prisma.CuisinetypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CuisinetypeInclude<ExtArgs> | null
  /**
   * The filter to search for the Cuisinetype to update in case it exists.
   */
  where: Prisma.CuisinetypeWhereUniqueInput
  /**
   * In case the Cuisinetype found by the `where` argument doesn't exist, create a new Cuisinetype with this data.
   */
  create: Prisma.XOR<Prisma.CuisinetypeCreateInput, Prisma.CuisinetypeUncheckedCreateInput>
  /**
   * In case the Cuisinetype was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CuisinetypeUpdateInput, Prisma.CuisinetypeUncheckedUpdateInput>
}

/**
 * Cuisinetype delete
 */
export type CuisinetypeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cuisinetype
   */
  select?: Prisma.CuisinetypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cuisinetype
   */
  omit?: Prisma.CuisinetypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CuisinetypeInclude<ExtArgs> | null
  /**
   * Filter which Cuisinetype to delete.
   */
  where: Prisma.CuisinetypeWhereUniqueInput
}

/**
 * Cuisinetype deleteMany
 */
export type CuisinetypeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Cuisinetypes to delete
   */
  where?: Prisma.CuisinetypeWhereInput
  /**
   * Limit how many Cuisinetypes to delete.
   */
  limit?: number
}

/**
 * Cuisinetype.meals
 */
export type Cuisinetype$mealsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Meal
   */
  select?: Prisma.MealSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Meal
   */
  omit?: Prisma.MealOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MealInclude<ExtArgs> | null
  where?: Prisma.MealWhereInput
  orderBy?: Prisma.MealOrderByWithRelationInput | Prisma.MealOrderByWithRelationInput[]
  cursor?: Prisma.MealWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MealScalarFieldEnum | Prisma.MealScalarFieldEnum[]
}

/**
 * Cuisinetype without action
 */
export type CuisinetypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cuisinetype
   */
  select?: Prisma.CuisinetypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cuisinetype
   */
  omit?: Prisma.CuisinetypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CuisinetypeInclude<ExtArgs> | null
}
