
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Dietrytype` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Dietrytype
 * 
 */
export type DietrytypeModel = runtime.Types.Result.DefaultSelection<Prisma.$DietrytypePayload>

export type AggregateDietrytype = {
  _count: DietrytypeCountAggregateOutputType | null
  _avg: DietrytypeAvgAggregateOutputType | null
  _sum: DietrytypeSumAggregateOutputType | null
  _min: DietrytypeMinAggregateOutputType | null
  _max: DietrytypeMaxAggregateOutputType | null
}

export type DietrytypeAvgAggregateOutputType = {
  id: number | null
}

export type DietrytypeSumAggregateOutputType = {
  id: number | null
}

export type DietrytypeMinAggregateOutputType = {
  id: number | null
  dietry_type_name: string | null
}

export type DietrytypeMaxAggregateOutputType = {
  id: number | null
  dietry_type_name: string | null
}

export type DietrytypeCountAggregateOutputType = {
  id: number
  dietry_type_name: number
  _all: number
}


export type DietrytypeAvgAggregateInputType = {
  id?: true
}

export type DietrytypeSumAggregateInputType = {
  id?: true
}

export type DietrytypeMinAggregateInputType = {
  id?: true
  dietry_type_name?: true
}

export type DietrytypeMaxAggregateInputType = {
  id?: true
  dietry_type_name?: true
}

export type DietrytypeCountAggregateInputType = {
  id?: true
  dietry_type_name?: true
  _all?: true
}

export type DietrytypeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Dietrytype to aggregate.
   */
  where?: Prisma.DietrytypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Dietrytypes to fetch.
   */
  orderBy?: Prisma.DietrytypeOrderByWithRelationInput | Prisma.DietrytypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DietrytypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Dietrytypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Dietrytypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Dietrytypes
  **/
  _count?: true | DietrytypeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DietrytypeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DietrytypeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DietrytypeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DietrytypeMaxAggregateInputType
}

export type GetDietrytypeAggregateType<T extends DietrytypeAggregateArgs> = {
      [P in keyof T & keyof AggregateDietrytype]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDietrytype[P]>
    : Prisma.GetScalarType<T[P], AggregateDietrytype[P]>
}




export type DietrytypeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DietrytypeWhereInput
  orderBy?: Prisma.DietrytypeOrderByWithAggregationInput | Prisma.DietrytypeOrderByWithAggregationInput[]
  by: Prisma.DietrytypeScalarFieldEnum[] | Prisma.DietrytypeScalarFieldEnum
  having?: Prisma.DietrytypeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DietrytypeCountAggregateInputType | true
  _avg?: DietrytypeAvgAggregateInputType
  _sum?: DietrytypeSumAggregateInputType
  _min?: DietrytypeMinAggregateInputType
  _max?: DietrytypeMaxAggregateInputType
}

export type DietrytypeGroupByOutputType = {
  id: number
  dietry_type_name: string
  _count: DietrytypeCountAggregateOutputType | null
  _avg: DietrytypeAvgAggregateOutputType | null
  _sum: DietrytypeSumAggregateOutputType | null
  _min: DietrytypeMinAggregateOutputType | null
  _max: DietrytypeMaxAggregateOutputType | null
}

type GetDietrytypeGroupByPayload<T extends DietrytypeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DietrytypeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DietrytypeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DietrytypeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DietrytypeGroupByOutputType[P]>
      }
    >
  >



export type DietrytypeWhereInput = {
  AND?: Prisma.DietrytypeWhereInput | Prisma.DietrytypeWhereInput[]
  OR?: Prisma.DietrytypeWhereInput[]
  NOT?: Prisma.DietrytypeWhereInput | Prisma.DietrytypeWhereInput[]
  id?: Prisma.IntFilter<"Dietrytype"> | number
  dietry_type_name?: Prisma.StringFilter<"Dietrytype"> | string
  meals?: Prisma.MealListRelationFilter
}

export type DietrytypeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  dietry_type_name?: Prisma.SortOrder
  meals?: Prisma.MealOrderByRelationAggregateInput
}

export type DietrytypeWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.DietrytypeWhereInput | Prisma.DietrytypeWhereInput[]
  OR?: Prisma.DietrytypeWhereInput[]
  NOT?: Prisma.DietrytypeWhereInput | Prisma.DietrytypeWhereInput[]
  dietry_type_name?: Prisma.StringFilter<"Dietrytype"> | string
  meals?: Prisma.MealListRelationFilter
}, "id">

export type DietrytypeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  dietry_type_name?: Prisma.SortOrder
  _count?: Prisma.DietrytypeCountOrderByAggregateInput
  _avg?: Prisma.DietrytypeAvgOrderByAggregateInput
  _max?: Prisma.DietrytypeMaxOrderByAggregateInput
  _min?: Prisma.DietrytypeMinOrderByAggregateInput
  _sum?: Prisma.DietrytypeSumOrderByAggregateInput
}

export type DietrytypeScalarWhereWithAggregatesInput = {
  AND?: Prisma.DietrytypeScalarWhereWithAggregatesInput | Prisma.DietrytypeScalarWhereWithAggregatesInput[]
  OR?: Prisma.DietrytypeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DietrytypeScalarWhereWithAggregatesInput | Prisma.DietrytypeScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Dietrytype"> | number
  dietry_type_name?: Prisma.StringWithAggregatesFilter<"Dietrytype"> | string
}

export type DietrytypeCreateInput = {
  dietry_type_name: string
  meals?: Prisma.MealCreateNestedManyWithoutDietry_relInput
}

export type DietrytypeUncheckedCreateInput = {
  id?: number
  dietry_type_name: string
  meals?: Prisma.MealUncheckedCreateNestedManyWithoutDietry_relInput
}

export type DietrytypeUpdateInput = {
  dietry_type_name?: Prisma.StringFieldUpdateOperationsInput | string
  meals?: Prisma.MealUpdateManyWithoutDietry_relNestedInput
}

export type DietrytypeUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  dietry_type_name?: Prisma.StringFieldUpdateOperationsInput | string
  meals?: Prisma.MealUncheckedUpdateManyWithoutDietry_relNestedInput
}

export type DietrytypeCreateManyInput = {
  id?: number
  dietry_type_name: string
}

export type DietrytypeUpdateManyMutationInput = {
  dietry_type_name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DietrytypeUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  dietry_type_name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DietrytypeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  dietry_type_name?: Prisma.SortOrder
}

export type DietrytypeAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type DietrytypeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  dietry_type_name?: Prisma.SortOrder
}

export type DietrytypeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  dietry_type_name?: Prisma.SortOrder
}

export type DietrytypeSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type DietrytypeScalarRelationFilter = {
  is?: Prisma.DietrytypeWhereInput
  isNot?: Prisma.DietrytypeWhereInput
}

export type DietrytypeCreateNestedOneWithoutMealsInput = {
  create?: Prisma.XOR<Prisma.DietrytypeCreateWithoutMealsInput, Prisma.DietrytypeUncheckedCreateWithoutMealsInput>
  connectOrCreate?: Prisma.DietrytypeCreateOrConnectWithoutMealsInput
  connect?: Prisma.DietrytypeWhereUniqueInput
}

export type DietrytypeUpdateOneRequiredWithoutMealsNestedInput = {
  create?: Prisma.XOR<Prisma.DietrytypeCreateWithoutMealsInput, Prisma.DietrytypeUncheckedCreateWithoutMealsInput>
  connectOrCreate?: Prisma.DietrytypeCreateOrConnectWithoutMealsInput
  upsert?: Prisma.DietrytypeUpsertWithoutMealsInput
  connect?: Prisma.DietrytypeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DietrytypeUpdateToOneWithWhereWithoutMealsInput, Prisma.DietrytypeUpdateWithoutMealsInput>, Prisma.DietrytypeUncheckedUpdateWithoutMealsInput>
}

export type DietrytypeCreateWithoutMealsInput = {
  dietry_type_name: string
}

export type DietrytypeUncheckedCreateWithoutMealsInput = {
  id?: number
  dietry_type_name: string
}

export type DietrytypeCreateOrConnectWithoutMealsInput = {
  where: Prisma.DietrytypeWhereUniqueInput
  create: Prisma.XOR<Prisma.DietrytypeCreateWithoutMealsInput, Prisma.DietrytypeUncheckedCreateWithoutMealsInput>
}

export type DietrytypeUpsertWithoutMealsInput = {
  update: Prisma.XOR<Prisma.DietrytypeUpdateWithoutMealsInput, Prisma.DietrytypeUncheckedUpdateWithoutMealsInput>
  create: Prisma.XOR<Prisma.DietrytypeCreateWithoutMealsInput, Prisma.DietrytypeUncheckedCreateWithoutMealsInput>
  where?: Prisma.DietrytypeWhereInput
}

export type DietrytypeUpdateToOneWithWhereWithoutMealsInput = {
  where?: Prisma.DietrytypeWhereInput
  data: Prisma.XOR<Prisma.DietrytypeUpdateWithoutMealsInput, Prisma.DietrytypeUncheckedUpdateWithoutMealsInput>
}

export type DietrytypeUpdateWithoutMealsInput = {
  dietry_type_name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DietrytypeUncheckedUpdateWithoutMealsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  dietry_type_name?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type DietrytypeCountOutputType
 */

export type DietrytypeCountOutputType = {
  meals: number
}

export type DietrytypeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  meals?: boolean | DietrytypeCountOutputTypeCountMealsArgs
}

/**
 * DietrytypeCountOutputType without action
 */
export type DietrytypeCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DietrytypeCountOutputType
   */
  select?: Prisma.DietrytypeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * DietrytypeCountOutputType without action
 */
export type DietrytypeCountOutputTypeCountMealsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MealWhereInput
}


export type DietrytypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  dietry_type_name?: boolean
  meals?: boolean | Prisma.Dietrytype$mealsArgs<ExtArgs>
  _count?: boolean | Prisma.DietrytypeCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dietrytype"]>

export type DietrytypeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  dietry_type_name?: boolean
}, ExtArgs["result"]["dietrytype"]>

export type DietrytypeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  dietry_type_name?: boolean
}, ExtArgs["result"]["dietrytype"]>

export type DietrytypeSelectScalar = {
  id?: boolean
  dietry_type_name?: boolean
}

export type DietrytypeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "dietry_type_name", ExtArgs["result"]["dietrytype"]>
export type DietrytypeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  meals?: boolean | Prisma.Dietrytype$mealsArgs<ExtArgs>
  _count?: boolean | Prisma.DietrytypeCountOutputTypeDefaultArgs<ExtArgs>
}
export type DietrytypeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type DietrytypeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $DietrytypePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Dietrytype"
  objects: {
    meals: Prisma.$MealPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    dietry_type_name: string
  }, ExtArgs["result"]["dietrytype"]>
  composites: {}
}

export type DietrytypeGetPayload<S extends boolean | null | undefined | DietrytypeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DietrytypePayload, S>

export type DietrytypeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DietrytypeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DietrytypeCountAggregateInputType | true
  }

export interface DietrytypeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Dietrytype'], meta: { name: 'Dietrytype' } }
  /**
   * Find zero or one Dietrytype that matches the filter.
   * @param {DietrytypeFindUniqueArgs} args - Arguments to find a Dietrytype
   * @example
   * // Get one Dietrytype
   * const dietrytype = await prisma.dietrytype.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DietrytypeFindUniqueArgs>(args: Prisma.SelectSubset<T, DietrytypeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DietrytypeClient<runtime.Types.Result.GetResult<Prisma.$DietrytypePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Dietrytype that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DietrytypeFindUniqueOrThrowArgs} args - Arguments to find a Dietrytype
   * @example
   * // Get one Dietrytype
   * const dietrytype = await prisma.dietrytype.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DietrytypeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DietrytypeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DietrytypeClient<runtime.Types.Result.GetResult<Prisma.$DietrytypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Dietrytype that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DietrytypeFindFirstArgs} args - Arguments to find a Dietrytype
   * @example
   * // Get one Dietrytype
   * const dietrytype = await prisma.dietrytype.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DietrytypeFindFirstArgs>(args?: Prisma.SelectSubset<T, DietrytypeFindFirstArgs<ExtArgs>>): Prisma.Prisma__DietrytypeClient<runtime.Types.Result.GetResult<Prisma.$DietrytypePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Dietrytype that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DietrytypeFindFirstOrThrowArgs} args - Arguments to find a Dietrytype
   * @example
   * // Get one Dietrytype
   * const dietrytype = await prisma.dietrytype.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DietrytypeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DietrytypeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DietrytypeClient<runtime.Types.Result.GetResult<Prisma.$DietrytypePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Dietrytypes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DietrytypeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Dietrytypes
   * const dietrytypes = await prisma.dietrytype.findMany()
   * 
   * // Get first 10 Dietrytypes
   * const dietrytypes = await prisma.dietrytype.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dietrytypeWithIdOnly = await prisma.dietrytype.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DietrytypeFindManyArgs>(args?: Prisma.SelectSubset<T, DietrytypeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DietrytypePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Dietrytype.
   * @param {DietrytypeCreateArgs} args - Arguments to create a Dietrytype.
   * @example
   * // Create one Dietrytype
   * const Dietrytype = await prisma.dietrytype.create({
   *   data: {
   *     // ... data to create a Dietrytype
   *   }
   * })
   * 
   */
  create<T extends DietrytypeCreateArgs>(args: Prisma.SelectSubset<T, DietrytypeCreateArgs<ExtArgs>>): Prisma.Prisma__DietrytypeClient<runtime.Types.Result.GetResult<Prisma.$DietrytypePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Dietrytypes.
   * @param {DietrytypeCreateManyArgs} args - Arguments to create many Dietrytypes.
   * @example
   * // Create many Dietrytypes
   * const dietrytype = await prisma.dietrytype.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DietrytypeCreateManyArgs>(args?: Prisma.SelectSubset<T, DietrytypeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Dietrytypes and returns the data saved in the database.
   * @param {DietrytypeCreateManyAndReturnArgs} args - Arguments to create many Dietrytypes.
   * @example
   * // Create many Dietrytypes
   * const dietrytype = await prisma.dietrytype.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Dietrytypes and only return the `id`
   * const dietrytypeWithIdOnly = await prisma.dietrytype.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DietrytypeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DietrytypeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DietrytypePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Dietrytype.
   * @param {DietrytypeDeleteArgs} args - Arguments to delete one Dietrytype.
   * @example
   * // Delete one Dietrytype
   * const Dietrytype = await prisma.dietrytype.delete({
   *   where: {
   *     // ... filter to delete one Dietrytype
   *   }
   * })
   * 
   */
  delete<T extends DietrytypeDeleteArgs>(args: Prisma.SelectSubset<T, DietrytypeDeleteArgs<ExtArgs>>): Prisma.Prisma__DietrytypeClient<runtime.Types.Result.GetResult<Prisma.$DietrytypePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Dietrytype.
   * @param {DietrytypeUpdateArgs} args - Arguments to update one Dietrytype.
   * @example
   * // Update one Dietrytype
   * const dietrytype = await prisma.dietrytype.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DietrytypeUpdateArgs>(args: Prisma.SelectSubset<T, DietrytypeUpdateArgs<ExtArgs>>): Prisma.Prisma__DietrytypeClient<runtime.Types.Result.GetResult<Prisma.$DietrytypePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Dietrytypes.
   * @param {DietrytypeDeleteManyArgs} args - Arguments to filter Dietrytypes to delete.
   * @example
   * // Delete a few Dietrytypes
   * const { count } = await prisma.dietrytype.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DietrytypeDeleteManyArgs>(args?: Prisma.SelectSubset<T, DietrytypeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Dietrytypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DietrytypeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Dietrytypes
   * const dietrytype = await prisma.dietrytype.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DietrytypeUpdateManyArgs>(args: Prisma.SelectSubset<T, DietrytypeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Dietrytypes and returns the data updated in the database.
   * @param {DietrytypeUpdateManyAndReturnArgs} args - Arguments to update many Dietrytypes.
   * @example
   * // Update many Dietrytypes
   * const dietrytype = await prisma.dietrytype.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Dietrytypes and only return the `id`
   * const dietrytypeWithIdOnly = await prisma.dietrytype.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DietrytypeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DietrytypeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DietrytypePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Dietrytype.
   * @param {DietrytypeUpsertArgs} args - Arguments to update or create a Dietrytype.
   * @example
   * // Update or create a Dietrytype
   * const dietrytype = await prisma.dietrytype.upsert({
   *   create: {
   *     // ... data to create a Dietrytype
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Dietrytype we want to update
   *   }
   * })
   */
  upsert<T extends DietrytypeUpsertArgs>(args: Prisma.SelectSubset<T, DietrytypeUpsertArgs<ExtArgs>>): Prisma.Prisma__DietrytypeClient<runtime.Types.Result.GetResult<Prisma.$DietrytypePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Dietrytypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DietrytypeCountArgs} args - Arguments to filter Dietrytypes to count.
   * @example
   * // Count the number of Dietrytypes
   * const count = await prisma.dietrytype.count({
   *   where: {
   *     // ... the filter for the Dietrytypes we want to count
   *   }
   * })
  **/
  count<T extends DietrytypeCountArgs>(
    args?: Prisma.Subset<T, DietrytypeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DietrytypeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Dietrytype.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DietrytypeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DietrytypeAggregateArgs>(args: Prisma.Subset<T, DietrytypeAggregateArgs>): Prisma.PrismaPromise<GetDietrytypeAggregateType<T>>

  /**
   * Group by Dietrytype.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DietrytypeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DietrytypeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DietrytypeGroupByArgs['orderBy'] }
      : { orderBy?: DietrytypeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DietrytypeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDietrytypeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Dietrytype model
 */
readonly fields: DietrytypeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Dietrytype.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DietrytypeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  meals<T extends Prisma.Dietrytype$mealsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Dietrytype$mealsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MealPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Dietrytype model
 */
export interface DietrytypeFieldRefs {
  readonly id: Prisma.FieldRef<"Dietrytype", 'Int'>
  readonly dietry_type_name: Prisma.FieldRef<"Dietrytype", 'String'>
}
    

// Custom InputTypes
/**
 * Dietrytype findUnique
 */
export type DietrytypeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dietrytype
   */
  select?: Prisma.DietrytypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dietrytype
   */
  omit?: Prisma.DietrytypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DietrytypeInclude<ExtArgs> | null
  /**
   * Filter, which Dietrytype to fetch.
   */
  where: Prisma.DietrytypeWhereUniqueInput
}

/**
 * Dietrytype findUniqueOrThrow
 */
export type DietrytypeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dietrytype
   */
  select?: Prisma.DietrytypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dietrytype
   */
  omit?: Prisma.DietrytypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DietrytypeInclude<ExtArgs> | null
  /**
   * Filter, which Dietrytype to fetch.
   */
  where: Prisma.DietrytypeWhereUniqueInput
}

/**
 * Dietrytype findFirst
 */
export type DietrytypeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dietrytype
   */
  select?: Prisma.DietrytypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dietrytype
   */
  omit?: Prisma.DietrytypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DietrytypeInclude<ExtArgs> | null
  /**
   * Filter, which Dietrytype to fetch.
   */
  where?: Prisma.DietrytypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Dietrytypes to fetch.
   */
  orderBy?: Prisma.DietrytypeOrderByWithRelationInput | Prisma.DietrytypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Dietrytypes.
   */
  cursor?: Prisma.DietrytypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Dietrytypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Dietrytypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Dietrytypes.
   */
  distinct?: Prisma.DietrytypeScalarFieldEnum | Prisma.DietrytypeScalarFieldEnum[]
}

/**
 * Dietrytype findFirstOrThrow
 */
export type DietrytypeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dietrytype
   */
  select?: Prisma.DietrytypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dietrytype
   */
  omit?: Prisma.DietrytypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DietrytypeInclude<ExtArgs> | null
  /**
   * Filter, which Dietrytype to fetch.
   */
  where?: Prisma.DietrytypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Dietrytypes to fetch.
   */
  orderBy?: Prisma.DietrytypeOrderByWithRelationInput | Prisma.DietrytypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Dietrytypes.
   */
  cursor?: Prisma.DietrytypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Dietrytypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Dietrytypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Dietrytypes.
   */
  distinct?: Prisma.DietrytypeScalarFieldEnum | Prisma.DietrytypeScalarFieldEnum[]
}

/**
 * Dietrytype findMany
 */
export type DietrytypeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dietrytype
   */
  select?: Prisma.DietrytypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dietrytype
   */
  omit?: Prisma.DietrytypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DietrytypeInclude<ExtArgs> | null
  /**
   * Filter, which Dietrytypes to fetch.
   */
  where?: Prisma.DietrytypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Dietrytypes to fetch.
   */
  orderBy?: Prisma.DietrytypeOrderByWithRelationInput | Prisma.DietrytypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Dietrytypes.
   */
  cursor?: Prisma.DietrytypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Dietrytypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Dietrytypes.
   */
  skip?: number
  distinct?: Prisma.DietrytypeScalarFieldEnum | Prisma.DietrytypeScalarFieldEnum[]
}

/**
 * Dietrytype create
 */
export type DietrytypeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dietrytype
   */
  select?: Prisma.DietrytypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dietrytype
   */
  omit?: Prisma.DietrytypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DietrytypeInclude<ExtArgs> | null
  /**
   * The data needed to create a Dietrytype.
   */
  data: Prisma.XOR<Prisma.DietrytypeCreateInput, Prisma.DietrytypeUncheckedCreateInput>
}

/**
 * Dietrytype createMany
 */
export type DietrytypeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Dietrytypes.
   */
  data: Prisma.DietrytypeCreateManyInput | Prisma.DietrytypeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Dietrytype createManyAndReturn
 */
export type DietrytypeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dietrytype
   */
  select?: Prisma.DietrytypeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Dietrytype
   */
  omit?: Prisma.DietrytypeOmit<ExtArgs> | null
  /**
   * The data used to create many Dietrytypes.
   */
  data: Prisma.DietrytypeCreateManyInput | Prisma.DietrytypeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Dietrytype update
 */
export type DietrytypeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dietrytype
   */
  select?: Prisma.DietrytypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dietrytype
   */
  omit?: Prisma.DietrytypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DietrytypeInclude<ExtArgs> | null
  /**
   * The data needed to update a Dietrytype.
   */
  data: Prisma.XOR<Prisma.DietrytypeUpdateInput, Prisma.DietrytypeUncheckedUpdateInput>
  /**
   * Choose, which Dietrytype to update.
   */
  where: Prisma.DietrytypeWhereUniqueInput
}

/**
 * Dietrytype updateMany
 */
export type DietrytypeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Dietrytypes.
   */
  data: Prisma.XOR<Prisma.DietrytypeUpdateManyMutationInput, Prisma.DietrytypeUncheckedUpdateManyInput>
  /**
   * Filter which Dietrytypes to update
   */
  where?: Prisma.DietrytypeWhereInput
  /**
   * Limit how many Dietrytypes to update.
   */
  limit?: number
}

/**
 * Dietrytype updateManyAndReturn
 */
export type DietrytypeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dietrytype
   */
  select?: Prisma.DietrytypeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Dietrytype
   */
  omit?: Prisma.DietrytypeOmit<ExtArgs> | null
  /**
   * The data used to update Dietrytypes.
   */
  data: Prisma.XOR<Prisma.DietrytypeUpdateManyMutationInput, Prisma.DietrytypeUncheckedUpdateManyInput>
  /**
   * Filter which Dietrytypes to update
   */
  where?: Prisma.DietrytypeWhereInput
  /**
   * Limit how many Dietrytypes to update.
   */
  limit?: number
}

/**
 * Dietrytype upsert
 */
export type DietrytypeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dietrytype
   */
  select?: Prisma.DietrytypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dietrytype
   */
  omit?: Prisma.DietrytypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DietrytypeInclude<ExtArgs> | null
  /**
   * The filter to search for the Dietrytype to update in case it exists.
   */
  where: Prisma.DietrytypeWhereUniqueInput
  /**
   * In case the Dietrytype found by the `where` argument doesn't exist, create a new Dietrytype with this data.
   */
  create: Prisma.XOR<Prisma.DietrytypeCreateInput, Prisma.DietrytypeUncheckedCreateInput>
  /**
   * In case the Dietrytype was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DietrytypeUpdateInput, Prisma.DietrytypeUncheckedUpdateInput>
}

/**
 * Dietrytype delete
 */
export type DietrytypeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dietrytype
   */
  select?: Prisma.DietrytypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dietrytype
   */
  omit?: Prisma.DietrytypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DietrytypeInclude<ExtArgs> | null
  /**
   * Filter which Dietrytype to delete.
   */
  where: Prisma.DietrytypeWhereUniqueInput
}

/**
 * Dietrytype deleteMany
 */
export type DietrytypeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Dietrytypes to delete
   */
  where?: Prisma.DietrytypeWhereInput
  /**
   * Limit how many Dietrytypes to delete.
   */
  limit?: number
}

/**
 * Dietrytype.meals
 */
export type Dietrytype$mealsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Meal
   */
  select?: Prisma.MealSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Meal
   */
  omit?: Prisma.MealOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MealInclude<ExtArgs> | null
  where?: Prisma.MealWhereInput
  orderBy?: Prisma.MealOrderByWithRelationInput | Prisma.MealOrderByWithRelationInput[]
  cursor?: Prisma.MealWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MealScalarFieldEnum | Prisma.MealScalarFieldEnum[]
}

/**
 * Dietrytype without action
 */
export type DietrytypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dietrytype
   */
  select?: Prisma.DietrytypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dietrytype
   */
  omit?: Prisma.DietrytypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DietrytypeInclude<ExtArgs> | null
}
